# -*- coding: utf-8 -*-
"""
完整工具契约 - 21工具
"""
from .tool_contract import ToolContract, TOOL_CONTRACTS

# 补充缺失的契约
MISSING_CONTRACTS = {
    "get_system_state": ToolContract(
        name="get_system_state",
        display_name="获取系统状态",
        description="获取真实系统状态，WMI+psutil",
        input_schema={"type": "object", "properties": {}},
        output_schema={"type": "object", "properties": {"cpu": {"type": "object"}, "memory": {"type": "object"}, "disk": {"type": "object"}}},
        side_effect="none",
        risk_level="low",
        timeout=5,
        required_permissions=["system_read"],
        preconditions=[],
        postconditions=["返回CPU内存磁盘"],
        verification_method="检查CPU内存字段存在，百分比合理0-100",
        category="系统状态",
        is_real=True,
        examples=["看看系统状态"]
    ),
    "read_file": ToolContract(
        name="read_file",
        display_name="读取文件",
        description="读取文本文件内容",
        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "max_chars": {"type": "integer", "default": 5000}}, "required": ["path"]},
        output_schema={"type": "object", "properties": {"content": {"type": "string"}, "length": {"type": "integer"}}},
        side_effect="none",
        risk_level="low",
        timeout=5,
        required_permissions=["file_read"],
        preconditions=["路径存在", "在白名单"],
        postconditions=["返回内容"],
        verification_method="检查content字段非空",
        category="文件管理",
        is_real=True,
        examples=["读取笔记"]
    ),
    "write_file": ToolContract(
        name="write_file",
        display_name="写入文件",
        description="写入文件，限制10MB，可撤销",
        input_schema={"type": "object", "properties": {"path": {"type": "string"}, "content": {"type": "string"}}, "required": ["path", "content"]},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}, "size": {"type": "integer"}}},
        side_effect="reversible",
        risk_level="medium",
        timeout=5,
        required_permissions=["file_write"],
        preconditions=["在沙盒白名单", "大小<10MB", "磁盘空间>100MB"],
        postconditions=["文件存在", "大小匹配"],
        verification_method="检查文件存在且大小一致",
        category="文件管理",
        is_real=True,
        examples=["创建文件"]
    ),
    "create_folder": ToolContract(
        name="create_folder",
        display_name="创建文件夹",
        description="创建文件夹",
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}, "required": ["path"]},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
        side_effect="reversible",
        risk_level="low",
        timeout=5,
        required_permissions=["file_write"],
        preconditions=["父目录在白名单"],
        postconditions=["文件夹存在"],
        verification_method="检查文件夹存在",
        category="文件管理",
        is_real=True,
        examples=["创建分类文件夹"]
    ),
    "move_file": ToolContract(
        name="move_file",
        display_name="移动文件",
        description="移动文件，可撤销",
        input_schema={"type": "object", "properties": {"source": {"type": "string"}, "dest": {"type": "string"}}, "required": ["source", "dest"]},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
        side_effect="reversible",
        risk_level="medium",
        timeout=10,
        required_permissions=["file_write"],
        preconditions=["源存在", "目标在白名单"],
        postconditions=["源不存在，目标存在"],
        verification_method="检查源不存在目标存在",
        category="文件管理",
        is_real=True,
        examples=["移动文件"]
    ),
    "ocr_screenshot": ToolContract(
        name="ocr_screenshot",
        display_name="OCR识别",
        description="OCR识别截图文字，中文",
        input_schema={"type": "object", "properties": {"image_path": {"type": "string"}, "lang": {"type": "string", "default": "chi_sim+eng"}}},
        output_schema={"type": "object", "properties": {"text": {"type": "string"}, "blocks": {"type": "array"}}},
        side_effect="none",
        risk_level="low",
        timeout=10,
        required_permissions=["screen_capture"],
        preconditions=["图片存在"],
        postconditions=["返回文字"],
        verification_method="检查text非空",
        category="视觉感知",
        is_real=True,
        examples=["识别屏幕文字"]
    ),
    "web_search": ToolContract(
        name="web_search",
        display_name="网络搜索演示",
        description="演示搜索，真实用web_search_real",
        input_schema={"type": "object", "properties": {"query": {"type": "string"}, "count": {"type": "integer", "default": 5}}, "required": ["query"]},
        output_schema={"type": "object", "properties": {"results": {"type": "array"}}},
        side_effect="none",
        risk_level="low",
        timeout=10,
        required_permissions=["network"],
        preconditions=[],
        postconditions=["返回结果"],
        verification_method="检查results非空",
        category="网络",
        is_real=False,
        examples=["搜索资料"]
    ),
    "web_search_real": ToolContract(
        name="web_search_real",
        display_name="真实联网搜索",
        description="Bing API优先+DuckDuckGo回退+防SSRF",
        input_schema={"type": "object", "properties": {"query": {"type": "string"}, "count": {"type": "integer", "default": 5}, "fetch_content": {"type": "boolean", "default": False}}, "required": ["query"]},
        output_schema={"type": "object", "properties": {"results": {"type": "array"}, "source": {"type": "string"}, "real": {"type": "boolean"}}},
        side_effect="none",
        risk_level="low",
        timeout=10,
        required_permissions=["network"],
        preconditions=["查询清理"],
        postconditions=["返回结果，防SSRF"],
        verification_method="检查results非空，source标记",
        category="网络",
        is_real=True,
        examples=["真实搜索Qwen3 MoE"]
    ),
    "security_scan": ToolContract(
        name="security_scan",
        display_name="安全扫描",
        description="扫描漏洞明文密码高危端口",
        input_schema={"type": "object", "properties": {"path": {"type": "string"}}},
        output_schema={"type": "object", "properties": {"issues": {"type": "array"}, "risk_level": {"type": "string"}}},
        side_effect="none",
        risk_level="low",
        timeout=15,
        required_permissions=["security_read"],
        preconditions=[],
        postconditions=["返回风险列表"],
        verification_method="检查issues字段",
        category="安全",
        is_real=True,
        examples=["扫描漏洞"]
    ),
    "wsl_exec": ToolContract(
        name="wsl_exec",
        display_name="WSL执行",
        description="WSL沙盒执行Linux命令，白名单",
        input_schema={"type": "object", "properties": {"distro": {"type": "string", "default": "Ubuntu"}, "command": {"type": "string"}, "workdir": {"type": "string", "default": "~"}}, "required": ["command"]},
        output_schema={"type": "object", "properties": {"stdout": {"type": "string"}, "stderr": {"type": "string"}, "returncode": {"type": "integer"}}},
        side_effect="none",
        risk_level="medium",
        timeout=10,
        required_permissions=["linux_exec"],
        preconditions=["命令在白名单ls/cat/grep", "无;|&><$"],
        postconditions=["返回stdout"],
        verification_method="检查returncode和stdout",
        category="Linux",
        is_real=True,
        examples=["执行ls -la"]
    ),
    "get_clipboard": ToolContract(
        name="get_clipboard",
        display_name="获取剪贴板",
        description="获取剪贴板内容",
        input_schema={"type": "object", "properties": {}},
        output_schema={"type": "object", "properties": {"content": {"type": "string"}}},
        side_effect="none",
        risk_level="low",
        timeout=2,
        required_permissions=["clipboard_read"],
        preconditions=[],
        postconditions=["返回内容"],
        verification_method="检查content字段",
        category="系统",
        is_real=True,
        examples=["获取剪贴板"]
    ),
    "set_clipboard": ToolContract(
        name="set_clipboard",
        display_name="设置剪贴板",
        description="设置剪贴板",
        input_schema={"type": "object", "properties": {"content": {"type": "string"}}, "required": ["content"]},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
        side_effect="reversible",
        risk_level="low",
        timeout=2,
        required_permissions=["clipboard_write"],
        preconditions=[],
        postconditions=["剪贴板已设置"],
        verification_method="检查success",
        category="系统",
        is_real=True,
        examples=["复制到剪贴板"]
    ),
    "mouse_click": ToolContract(
        name="mouse_click",
        display_name="鼠标点击",
        description="鼠标点击坐标",
        input_schema={"type": "object", "properties": {"x": {"type": "integer"}, "y": {"type": "integer"}} , "required": ["x", "y"]},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
        side_effect="reversible",
        risk_level="medium",
        timeout=2,
        required_permissions=["input_control"],
        preconditions=["坐标在屏幕内"],
        postconditions=["已点击"],
        verification_method="API返回success",
        category="输入控制",
        is_real=True,
        examples=["点击按钮"]
    ),
    "keyboard_input": ToolContract(
        name="keyboard_input",
        display_name="键盘输入",
        description="键盘输入文字或按键",
        input_schema={"type": "object", "properties": {"text": {"type": "string"}, "keys": {"type": "string"}}},
        output_schema={"type": "object", "properties": {"success": {"type": "boolean"}}},
        side_effect="reversible",
        risk_level="medium",
        timeout=2,
        required_permissions=["input_control"],
        preconditions=[],
        postconditions=["已输入"],
        verification_method="API返回success",
        category="输入控制",
        is_real=True,
        examples=["输入文字"]
    ),
    "verify_info": ToolContract(
        name="verify_info",
        display_name="信息验证",
        description="验证信息真实性",
        input_schema={"type": "object", "properties": {"claim": {"type": "string"}}, "required": ["claim"]},
        output_schema={"type": "object", "properties": {"verified": {"type": "boolean"}, "confidence": {"type": "number"}}},
        side_effect="none",
        risk_level="low",
        timeout=10,
        required_permissions=[],
        preconditions=[],
        postconditions=["返回验证结果"],
        verification_method="检查verified字段",
        category="验证",
        is_real=False,
        examples=["验证信息"]
    ),
}

# 合并到全局
TOOL_CONTRACTS.update(MISSING_CONTRACTS)
